student_count = 11
puts "The students of Villians Academy"
puts "------------------"
puts "Dr. Hannibal Lector"
puts "Darth Vader"
puts "Nurse Ratched"
puts "Michael Corleone"
puts "Alex Delarge"
puts "The Wicked Witch of the West"
puts "Terminator"
puts "Freddy Krueger"
puts "The Joker"
puts "Joffrey Baratheon"
puts "Norman Bates"
print "Overall, we have #{student_count} great students" 
